name: update changelog

on:
  push:
    branches: [ "main", "developement" ]
  pull_request:
    branches: [ "main", "developement" ]

permissions: {}

jobs:
  php_test:
    uses: phoenixrhein/xt-github-action/.github/workflows/phpci.yml@main
