name: update changelog

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

permissions: {}

jobs:
  php_test:
    uses: phoenixrhein/xt-github-action/.github/workflows/phpci.yml@1.2.0
    secrets:
      REPO_READ_TOKEN: ${{ secrets.REPO_READ_TOKEN }}   
